version: '2'
volumes:
  cake-logs:
  cake-tmp:
  mysql-volume:
services:
  web:
    build: web
    image: travel_base_system_web
    container_name: travel_base_system_web
    tty: true
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - ../:/var/www/html/
      - cake-logs:/var/www/html/logs
      - cake-tmp:/var/www/html/tmp
  web-debug:
    build: web-debug
    image: travel_base_system_web_debug
    container_name: travel_base_system_web_debug
    tty: true
    depends_on:
      - web
      - db
    ports:
      - 8080:80
    volumes:
      - ../:/var/www/html/
      - cake-logs:/var/www/html/logs
      - cake-tmp:/var/www/html/tmp
  db:
    build: db
    image: travel_base_system_db
    container_name: travel_base_system_db
    tty: true
    volumes:
      - mysql-volume:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
